from .merge_result import Combine_results
from .BOW_algorithm import Recommendation_BOW
from .idf_algorithm import Recommendation_IDF
from .TF_IDF_algorithm import Recommendation_TFIDF
from .avg_word2vec_algorithm import Recommendation_word2vec
from .another_feature import Recommend_with_features
from .Deep_Learning_vgg16 import Deep_Learning_VGG16
from .weighted_word2vec import Recommendation_weighted_word2vec